apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: registry-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2.6
        imagePullPolicy: IfNotPresent
